language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

php:
  - '5.5'
  - '5.6'
  - '7.0'
  - 'hhvm'

env:
  - SYMFONY_VERSION=locked # Use the versions that are given in composer.lock.
  - SYMFONY_VERSION="2.3.*"
  - SYMFONY_VERSION="2.4.*"
  - SYMFONY_VERSION="2.5.*"
  - SYMFONY_VERSION="2.6.*"
  - SYMFONY_VERSION="2.7.*"
  - SYMFONY_VERSION="2.8.*"

before_script:
    - composer self-update
    - composer install --no-interaction --prefer-source
    # Register a specific Symfony version if necessary...
    - sh -c "if [ '$SYMFONY_VERSION' != 'locked' ]; then composer require --no-update symfony/symfony:${SYMFONY_VERSION}; fi"
      # ... and update the dependencies accordingly.
    - sh -c "if [ '$SYMFONY_VERSION' != 'locked' ]; then composer update --no-interaction --prefer-source; fi"
    - mkdir -p build/logs

script:
    - composer validate --strict
    - vendor/bin/phpunit --coverage-clover build/logs/clover.xml

matrix:
  allow_failures:
    - php: hhvm

notifications:
  hipchat:
    rooms:
      secure: "U6zvjfNRPKPAdsl1NFDR2uFXsKUVwo2/+/S3M8Ovep6Iualsq3T21Gg/Bvll1IqJRY07aOFMkedQZYEP++mNzweNfPxHZAw47UEV4LO9B3R7VdpYO5VodEKAU/KAvnJBOv+/GFVatbVDsppk55E/Qu/x7ZniUm1O8Yhnw26vLjg="
