language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

php:
  - '7.2'

env:
  - SYMFONY_VERSION=locked PHPUNIT_VERSION=locked # Use the versions that are given in composer.lock.
  - SYMFONY_VERSION="2.8.*" PHPUNIT_VERSION="^7.4.0"
  - SYMFONY_VERSION="3.4.*" PHPUNIT_VERSION="^7.4.0"

before_script:
  - sh -c "if [ '$TRAVIS_PHP_VERSION' != 'hhvm' ] && [ -f 'travis.php.ini' ]; then phpenv config-add travis.php.ini; fi"
  - composer self-update
  - sh -c "if [ '$SYMFONY_VERSION' = 'locked' ]; then composer install --no-interaction --prefer-source; fi"
  # Register a specific dependency versions if necessary...
  - sh -c "if [ '$SYMFONY_VERSION' != 'locked' ]; then composer require --no-update symfony/symfony:${SYMFONY_VERSION} phpunit/phpunit:${PHPUNIT_VERSION}; fi"
    # ... and update the dependencies accordingly, without restrictions regarding the PHP version.
  - sh -c "if [ '$SYMFONY_VERSION' != 'locked' ]; then composer config --unset platform.php; composer update --no-interaction --prefer-source; fi"
  - mkdir -p build/logs

script:
  - composer validate --strict
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml
